name: Build APK

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde9182f3b5b69ebf9a1a715a2c4cba3e2e4d

      - name: Setup JDK 17
        uses: actions/setup-java@563bae933b5aaefffc9c1b173a8d8de6dbf4d8a5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@5f62e0ffde2c19fb655ff1989fda23d6d5acb63d
        with:
          name: FoodZone-APK
          path: app/build/outputs/apk/debug/app-debug.apk
